2020-11-16 20:37:48 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-16 20:37:48 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-16 20:37:48 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for wiser which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-16 20:37:48 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for circadian_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-16 20:37:48 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for apple_tv which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-16 20:37:48 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for entity_controller which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-16 20:37:53 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for bwalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-16 20:37:56 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for iphonedetect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-16 20:37:57 WARNING (MainThread) [homeassistant.components.switch] SwitchDevice is deprecated, modify WiserSwitch to extend SwitchEntity
2020-11-16 20:37:57 WARNING (MainThread) [homeassistant.components.switch] SwitchDevice is deprecated, modify WiserSmartPlug to extend SwitchEntity
2020-11-16 20:37:57 WARNING (MainThread) [homeassistant.components.climate] ClimateDevice is deprecated, modify WiserRoom to extend ClimateEntity
2020-11-16 20:37:58 WARNING (MainThread) [pyatv.mrp.player_state] Received UpdateClientMessage for unknown player com.itv.itvplayer
2020-11-16 20:37:58 WARNING (MainThread) [pyatv.mrp.player_state] Received UpdateClientMessage for unknown player com.bskyb.nowtv.appletv
2020-11-16 20:37:58 WARNING (MainThread) [pyatv.mrp.player_state] Received UpdateClientMessage for unknown player uk.co.bbc.iplayer
2020-11-16 20:37:59 WARNING (MainThread) [pyatv.mrp.player_state] Received UpdateClientMessage for unknown player com.apple.TVAirPlay
2020-11-16 20:37:59 ERROR (MainThread) [custom_components.entity_controller.lounge_front_light] Configuration error! State Entity ('NoneType' object has no attribute 'state') does not exist. Please check for spelling and typos.
2020-11-16 20:37:59 ERROR (MainThread) [custom_components.entity_controller.lounge_back_light] Configuration error! State Entity ('NoneType' object has no attribute 'state') does not exist. Please check for spelling and typos.
2020-11-16 20:38:09 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.niemand_front_door is taking over 10 seconds
2020-11-16 20:38:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-16 20:58:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2770515736] Pause failed: SendError=ApplicationNotFound, HandlerReturnStatus=Success
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 482, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 519, in _handle_entity_call
    await result
  File "/config/custom_components/apple_tv/media_player.py", line 269, in async_media_play_pause
    await self.atv.remote_control.pause()
  File "/usr/local/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 212, in pause
    await self._send_command(CommandInfo_pb2.Pause)
  File "/usr/local/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 170, in _send_command
    raise exceptions.CommandError(
pyatv.exceptions.CommandError: Pause failed: SendError=ApplicationNotFound, HandlerReturnStatus=Success
2020-11-16 20:58:53 WARNING (MainThread) [pyatv.mrp.player_state] Received UpdateClientMessage for unknown player com.itv.itvplayer
2020-11-16 20:58:53 WARNING (MainThread) [pyatv.mrp.player_state] Received UpdateClientMessage for unknown player com.bskyb.nowtv.appletv
2020-11-16 20:58:53 WARNING (MainThread) [pyatv.mrp.player_state] Received UpdateClientMessage for unknown player uk.co.bbc.iplayer
2020-11-16 20:58:53 WARNING (MainThread) [pyatv.mrp.player_state] Received UpdateClientMessage for unknown player com.apple.TVAirPlay
2020-11-16 21:01:34 ERROR (MainThread) [homeassistant.helpers.event] Error while processing state changed for media_player.living_room
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 258, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 434, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 199, in state_change_listener
    hass.async_run_hass_job(
  File "/usr/src/homeassistant/homeassistant/core.py", line 434, in async_run_hass_job
    hassjob.target(*args)
  File "/config/custom_components/entity_controller/__init__.py", line 540, in sensor_state_change
    self.log.debug("sensor_state_change :: %10s Sensor state change to: %s" % ( pprint.pformat(entity), new.state))
AttributeError: 'NoneType' object has no attribute 'state'
2020-11-16 21:01:34 ERROR (MainThread) [homeassistant.helpers.event] Error while processing state changed for media_player.living_room
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 258, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 434, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 199, in state_change_listener
    hass.async_run_hass_job(
  File "/usr/src/homeassistant/homeassistant/core.py", line 434, in async_run_hass_job
    hassjob.target(*args)
  File "/config/custom_components/entity_controller/__init__.py", line 540, in sensor_state_change
    self.log.debug("sensor_state_change :: %10s Sensor state change to: %s" % ( pprint.pformat(entity), new.state))
AttributeError: 'NoneType' object has no attribute 'state'
2020-11-16 21:01:34 ERROR (MainThread) [homeassistant.components.media_player] Platform apple_tv does not generate unique IDs. ID mp_444C4565-7251-4E47-8E2B-CB9244FBF47F already exists - ignoring media_player.living_room
2020-11-16 21:18:23 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:18:59 WARNING (SyncWorker_21) [homeassistant.components.ring] Error fetching Ring history data for device 3ce1a1b15dd6: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/doorbots/52497214/history?api_version=9&limit=10
2020-11-16 21:19:59 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring device data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/ring_devices?api_version=9
2020-11-16 21:21:48 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:24:59 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring device data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/ring_devices?api_version=9
2020-11-16 21:25:58 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:26:59 WARNING (SyncWorker_50) [homeassistant.components.ring] Error fetching Ring history data for device 3ce1a1aa01e6: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/doorbots/29555823/history?api_version=9&limit=10
2020-11-16 21:28:43 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:28:59 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring device data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/ring_devices?api_version=9
2020-11-16 21:29:03 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:29:23 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:29:53 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:30:03 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:30:23 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:30:33 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:30:53 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:30:59 WARNING (SyncWorker_17) [homeassistant.components.ring] Error fetching Ring history data for device 3ce1a1b15dd6: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/doorbots/52497214/history?api_version=9&limit=10
2020-11-16 21:31:09 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-16 21:31:09 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-16 21:31:13 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:31:18 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:31:33 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:31:48 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:31:59 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring device data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/ring_devices?api_version=9
2020-11-16 21:31:59 WARNING (SyncWorker_16) [homeassistant.components.ring] Error fetching Ring history data for device 3ce1a1b15dd6: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/doorbots/52497214/history?api_version=9&limit=10
2020-11-16 21:32:08 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:32:23 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:32:38 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:32:43 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:32:48 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:32:59 WARNING (SyncWorker_12) [homeassistant.components.ring] Error fetching Ring history data for device 3ce1a1b15dd6: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/doorbots/52497214/history?api_version=9&limit=10
2020-11-16 21:32:59 WARNING (SyncWorker_12) [homeassistant.components.ring] Error fetching Ring history data for device 3ce1a1aa01e6: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/doorbots/29555823/history?api_version=9&limit=10
2020-11-16 21:32:59 WARNING (SyncWorker_12) [homeassistant.components.ring] Error fetching Ring history data for device 3ce1a11d2411: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/doorbots/21044527/history?api_version=9&limit=10
2020-11-16 21:33:03 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 21:33:18 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 503 Server Error: Service Temporarily Unavailable for url: https://api.ring.com/clients_api/dings/active?api_version=9
2020-11-16 22:17:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-16 23:04:00 WARNING (SyncWorker_50) [homeassistant.components.ring] Error fetching Ring history data for device 3ce1a1aa01e6: 401 Client Error: Unauthorized for url: https://api.ring.com/clients_api/doorbots/29555823/history?api_version=9&limit=10
2020-11-16 23:06:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-16 23:06:10 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-16 23:07:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-16 23:09:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-16 23:09:10 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-16 23:11:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-16 23:11:10 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-16 23:12:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-16 23:12:10 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-16 23:13:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-16 23:13:10 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-16 23:18:12 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-16 23:20:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-16 23:20:10 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-16 23:25:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-16 23:25:10 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-16 23:26:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-16 23:38:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.niemand_front_door is taking over 10 seconds
2020-11-16 23:44:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-16 23:44:11 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-16 23:48:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-16 23:48:11 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-16 23:56:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-16 23:56:11 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-16 23:57:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 00:43:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 00:53:57 ERROR (MainThread) [homeassistant.components.accuweather] Error fetching accuweather data: The allowed number of requests has been exceeded
2020-11-17 01:20:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.front_door is taking over 10 seconds
2020-11-17 01:20:11 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.front_door
2020-11-17 01:29:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 02:01:36 ERROR (MainThread) [custom_components.wiser.const] Unable to update from Wiser hub due to timeout error
2020-11-17 02:14:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 02:38:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.niemand_front_door is taking over 10 seconds
2020-11-17 02:39:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.front_door is taking over 10 seconds
2020-11-17 02:39:11 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.front_door
2020-11-17 02:55:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 02:55:11 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-17 02:56:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 03:04:01 WARNING (SyncWorker_27) [homeassistant.components.ring] Error fetching Ring history data for device 3ce1a1b15dd6: 401 Client Error: Unauthorized for url: https://api.ring.com/clients_api/doorbots/52497214/history?api_version=9&limit=10
2020-11-17 03:08:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 03:08:11 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-17 03:22:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 03:22:12 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-17 03:23:10 ERROR (MainThread) [custom_components.wiser.const] Unable to update from Wiser hub due to unknown error
2020-11-17 03:23:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 03:23:12 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-17 03:25:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 03:25:12 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-17 03:29:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 03:29:12 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-17 03:36:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 03:36:12 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-17 03:40:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 03:40:12 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-17 03:43:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 03:43:12 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-17 03:46:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 03:46:12 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-17 03:48:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 03:48:12 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-17 03:49:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 03:55:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 03:55:12 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-17 04:00:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 04:00:12 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-17 04:07:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 04:07:12 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-17 04:08:13 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 04:39:13 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.front_door is taking over 10 seconds
2020-11-17 04:39:13 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.front_door
2020-11-17 05:15:13 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 05:15:13 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.johan_front_door
2020-11-17 05:16:13 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 05:38:13 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.niemand_front_door is taking over 10 seconds
2020-11-17 06:01:13 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.johan_front_door is taking over 10 seconds
2020-11-17 06:30:13 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.front_door is taking over 10 seconds
2020-11-17 06:30:13 WARNING (MainThread) [homeassistant.components.ring.camera] Time out fetching recording url for camera camera.front_door
2020-11-17 06:49:42 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.average_ping_konnected_main_ratio fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 224, in update
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/history/__init__.py", line 169, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 31, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable
2020-11-17 06:49:42 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.average_ping_konnected_main_count fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 224, in update
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/history/__init__.py", line 169, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 31, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable
2020-11-17 06:49:42 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.average_ping_konnected_addon_ratio fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 224, in update
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/history/__init__.py", line 169, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 31, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable
2020-11-17 06:49:42 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.average_ping_konnected_addon_count fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 224, in update
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/history/__init__.py", line 169, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 31, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable
2020-11-17 06:49:45 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.average_ping_konnected_google_ratio fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 224, in update
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/history/__init__.py", line 169, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 31, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable
2020-11-17 06:49:45 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.average_ping_konnected_google_count fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 224, in update
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/history/__init__.py", line 169, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 31, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable
